# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170507_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(default='something', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default='something', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='picture',
            field=models.ImageField(null=True, upload_to='Store-picture', verbose_name='Image'),
        ),
    ]
