# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170528_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.IntegerField(default=17.385, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='lng',
            field=models.IntegerField(default=78.4867, verbose_name='Longitude'),
        ),
    ]
