# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170528_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=17.385, max_digits=8, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='lng',
            field=models.DecimalField(decimal_places=4, default=78.4867, max_digits=8, verbose_name='Longitude'),
        ),
    ]
