# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_auto_20170528_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='token',
            field=models.CharField(max_length=256, null=True, verbose_name='Token'),
        ),
    ]
