# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20170529_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Token'),
        ),
    ]
