# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.TextField(default='', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
