# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20170616_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lng',
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default='', max_length=256, verbose_name='City'),
        ),
    ]
