# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20170616_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Store-picture', verbose_name='Store Image'),
        ),
    ]
