# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20170617_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hours',
            field=models.CharField(default='', max_length=256, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='postal',
            field=models.PositiveIntegerField(default=0, verbose_name='Postal'),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(default='', max_length=256, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='store',
            name='street',
            field=models.CharField(default='', max_length=256, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(default='', max_length=256, verbose_name='Website'),
        ),
    ]
