# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20170722_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Available Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax'),
        ),
    ]
