# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20170803_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='return_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Return Days'),
        ),
    ]
