# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20170809_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_product', to='store.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('F', 'Franchise'), ('S', 'Store')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='store.Store'),
        ),
    ]
