# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20170809_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='franchise',
        ),
        migrations.AddField(
            model_name='product',
            name='store_chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_product', to='store.Franchise', verbose_name='Franchise'),
        ),
        migrations.AlterField(
            model_name='product',
            name='infinite_quantity',
            field=models.BooleanField(default=False, help_text='Is the quantity infinite? ie. Quantity depends on demand.', verbose_name='Infinite Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('F', 'Franchise'), ('S', 'Store')], help_text='Whether the product belongs to a individual store or a Franchise?', max_length=1),
        ),
    ]
