# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_franchisestoreproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchisestoreproduct',
            old_name='store',
            new_name='franchise_store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='store.Store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_product', to='store.Franchise', verbose_name='Franchise'),
        ),
    ]
