# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20170810_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchisestoreproduct',
            name='franchise_store',
        ),
        migrations.RemoveField(
            model_name='franchisestoreproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='FranchiseStoreProduct',
        ),
    ]
