# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20170810_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Available Quantity'),
        ),
    ]
