# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20170902_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='franchise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.FranchiseType'),
        ),
    ]
