# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20170918_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='store.ProductCategory'),
        ),
    ]
