# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 06:42
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Choose your country code by clicking on the menu above.', max_length=128),
        ),
    ]
