# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170507_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile-picture', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Choose your country code by clicking on the menu above.', max_length=128, verbose_name='Phone number'),
        ),
    ]
