# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow')),
                ('url', models.URLField(blank=True)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Banner')),
            ],
        ),
    ]
