# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20170705_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='fsasdf', verbose_name='Address'),
            preserve_default=False,
        ),
    ]
