# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 09:04
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20170722_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Choose your country code by clicking on the menu above.', max_length=128, unique=True, verbose_name='Phone number'),
        ),
    ]
