# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0002_auto_20170529_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='store.Store'),
        ),
    ]
