# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20170529_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
