# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='bills.Bill'),
        ),
    ]
