# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_product_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bills.Bill'),
        ),
    ]
