# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20170530_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.Bill')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='bill',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
