# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_auto_20170602_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
