# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_bill_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='original',
            field=models.BooleanField(default=True),
        ),
    ]
