# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_auto_20170709_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
