# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_auto_20170803_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
