# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_auto_20170810_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
