# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('latitude', models.CharField(max_length=70)),
                ('longitude', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70, verbose_name='City/Suburb')),
                ('state', models.CharField(max_length=70, verbose_name='State/Region')),
                ('postal', models.CharField(max_length=70, verbose_name='Zip/Postcode')),
                ('phone', models.CharField(blank=True, max_length=70)),
                ('website', models.CharField(blank=True, max_length=70)),
                ('hours', models.CharField(blank=True, max_length=70)),
            ],
        ),
    ]
